[application]

style =  ["./tailwind.css"]

[web.app]

# HTML title tag content
title = "archeology"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = ["./tailwind.css"]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
[desktop.app]
style = ["main.css"]